apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-config
data:
  httpd.conf: |
    # Cargar módulos necesarios
    LoadModule auth_basic_module modules/mod_auth_basic.so
    LoadModule mpm_event_module modules/mod_mpm_event.so
    LoadModule proxy_module modules/mod_proxy.so
    LoadModule proxy_http_module modules/mod_proxy_http.so
    LoadModule unixd_module modules/mod_unixd.so
    LoadModule authz_core_module modules/mod_authz_core.so
    LoadModule ssl_module modules/mod_ssl.so
    LoadModule alias_module modules/mod_alias.so
    LoadModule authn_core_module modules/mod_authn_core.so
    LoadModule authn_file_module modules/mod_authn_file.so
    LoadModule authz_user_module modules/mod_authz_user.so
    LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so
    LoadModule rewrite_module modules/mod_rewrite.so
    LoadModule dir_module modules/mod_dir.so
    LoadModule log_config_module modules/mod_log_config.so

    # Configuración básica
    ServerRoot "/usr/local/apache2"
    User www-data
    Group www-data
    Listen 80
    Listen 443
    ServerName localhost

    # Habilitar logs
    ErrorLog /proc/self/fd/2 
    CustomLog /proc/self/fd/1 common 
    LogLevel debug

    # VirtualHost para bego.work.gd app
    <VirtualHost *:80>
        ServerName www.begona.work.gd

        #ErrorLog /usr/local/apache2/logs/begona_error.log

        Redirect permanent / https://begona.work.gd/

    </VirtualHost>

    # VirtualHost https para bego.work.gd
    <VirtualHost *:443>
        ServerName www.begona.work.gd

        DocumentRoot /var/www/html/symfony/public
        DirectoryIndex index.php index.html

        <Directory /var/www/html/symfony/public>
            Options Indexes FollowSymLinks
            AllowOverride None
            Require all granted

            #el allowOverride none de arriba y esta seccion de abajo es porque no tenemos un .htaccess en la app de symfony
            #por lo que apache no sabe redirigir el trafico. Con esto se soluciona
            <IfModule mod_rewrite.c>
               RewriteEngine On
                RewriteCond %{REQUEST_FILENAME} !-f
                RewriteCond %{REQUEST_FILENAME} !-d
                RewriteRule ^(.*)$ index.php [QSA,L]
            </IfModule>
        </Directory>

        # Configurar proxy a PHP. Tienes que poner el mismo nombre que en el docker compose en este caso php
        <FilesMatch \.php$>
            SetHandler "proxy:fcgi://localhost:9000"
        </FilesMatch>

        SSLEngine on
        SSLCertificateFile /usr/local/apache2/certs/begona/begona.work.gd.cer
        SSLCertificateKeyFile /usr/local/apache2/certs/begona/begona.work.gd.key
        SSLCertificateChainFile /usr/local/apache2/certs/begona/ca.cer

        #ErrorLog /usr/local/apache2/logs/bego_error.log
    </VirtualHost>     