apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-deployment 
  labels:
    app: symfony-web 
spec:
  revisionHistoryLimit: 2 
  strategy:
    type: RollingUpdate 
  replicas: 2 
  selector:
    matchLabels:
      app: symfony-web 
  template:
    metadata:
      labels:
        app: symfony-web 
    spec:
      securityContext: # para los permisos de las carpetas
        fsGroup: 33
      containers:
      # Contenedor de Apache
      - name: apache 
        image: bego13/apache-symfony:latest 
        ports:
        - containerPort: 80 
        - containerPort: 443 
        volumeMounts:
        # Volumen para el congif map
        - name: apache-config-volume
          mountPath: /usr/local/apache2/conf/httpd.conf
          subPath: httpd.conf 
        # Volumen para la app en el efs
        - name: efs-symfony-volume
          mountPath: /var/www/html/symfony

      # Contenedor de PHP-FPM
      - name: phpfpm 
        image: bego13/phpfpm-symfony:latest
        ports:
        - containerPort: 9000
        env: #  Variables de entorno para PHP-FPM
        - name: DATABASE_URL
          value: "mysql://admin:adminadmin@rds-service:3306/mywallcopia?serverVersion=11.4.5-MariaDB&charset=utf8mb4"
        - name: APP_ENV
          value: "prod" # Para EKS siempre en producción
        - name: APP_SECRET
          value: "esteEsMiSecretoLargoYSeguro"
        volumeMounts:
        # Volumen para la app en el efs
        - name: efs-symfony-volume
          mountPath: /var/www/html/symfony

      # Definición de los volumenes a montar
      volumes:
      - name: apache-config-volume
        configMap:
          name: apache-config

      - name: efs-symfony-volume
        persistentVolumeClaim:
          claimName: efs-pvc 