apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpfpm-deployment
  labels:
    app: phpfpm
spec:
  revisionHistoryLimit: 2
  strategy: 
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: phpfpm
  template:
    metadata:
      labels:
        app: phpfpm
    spec:
      containers:
      - name: phpfpm
        image: bego13/phpfpm-symfony:latest
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: symfony-app
          mountPath: /var/www/html  # donde tu app debe estar en el contenedor
      volumes:
      - name: symfony-app
        persistentVolumeClaim:
          claimName: efs-pvc