apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-config
data:
  httpd.conf: |
    # Cargar módulos necesarios
    LoadModule auth_basic_module modules/mod_auth_basic.so
    LoadModule mpm_event_module modules/mod_mpm_event.so
    LoadModule proxy_module modules/mod_proxy.so
    LoadModule proxy_http_module modules/mod_proxy_http.so
    LoadModule unixd_module modules/mod_unixd.so
    LoadModule authz_core_module modules/mod_authz_core.so
    LoadModule ssl_module modules/mod_ssl.so
    LoadModule alias_module modules/mod_alias.so
    LoadModule authn_core_module modules/mod_authn_core.so
    LoadModule authn_file_module modules/mod_authn_file.so
    LoadModule authz_user_module modules/mod_authz_user.so
    LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so

    # Configuración básica
    ServerRoot "/usr/local/apache2"
    User www-data
    Group www-data
    Listen 80
    Listen 443
    ServerName localhost

    # Habilitar logs
    ErrorLog /usr/local/apache2/logs/error.log
    LogLevel debug

    # VirtualHost para bego.work.gd app
    <VirtualHost *:80>
        ServerName begona.work.gd

        ErrorLog /usr/local/apache2/logs/bego_error.log

        Redirect permanent / https://begona.work.gd/

    </VirtualHost>

    # VirtualHost https para bego.work.gd
    <VirtualHost *:443>
        ServerName begona.work.gd

        DocumentRoot /var/www/html/public

        <Directory /var/www/html/public>
            Options Indexes FollowSymLinks
            AllowOverride All
            Require all granted
        </Directory>

        # Configurar proxy a PHP-FPM
        <FilesMatch \.php$>
            SetHandler "proxy:fcgi://phpfpm:9000"
        </FilesMatch>

        SSLEngine on
        SSLCertificateFile /usr/local/apache2/certs/begona/begona.work.gd.cer
        SSLCertificateKeyFile /usr/local/apache2/certs/begona/begona.work.gd.key
        SSLCertificateChainFile /usr/local/apache2/certs/begona/ca.cer

        ErrorLog /usr/local/apache2/logs/bego_error.log
    </VirtualHost>    