apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
spec:
  revisionHistoryLimit: 2
  strategy: 
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4
        ports:
        - containerPort: 80
        - containerPort: 443
        #aqui es donde se va a montar en el contenedor el volumen cargado abajo (el configMap con la configuracion de apache)
        volumeMounts:
        - name: apache-config-volume
          mountPath: /usr/local/apache2/conf/httpd.conf
          subPath: httpd.conf
      #esto hace referencia al configMap. Estamos cargando un volumen que es el congifmap
      volumes:
      - name: apache-config-volume
        configMap:
          name: apache-config